FIND_PACKAGE(GLEW REQUIRED)
INCLUDE_DIRECTORIES(${GLEW_INCLUDE_DIRS})
LINK_LIBRARIES(${GLEW_LIBRARIES})

LIST(APPEND stdgl_libraries ${GLEW_LIBRARIES})

message(STATUS "GLEW_LIBRARIES=${GLEW_LIBRARIES}")
